"""Type stub for ``buddy_ui_cp``, vendored upstream on the device's flash.

Reused byte-for-byte from the Basic build (see ``apps/claude_buddy.py``'s
docstring); not shipped from this repository. Only the members
``apps/claude_buddy.py`` touches are declared.
"""

BLACK: int
GRAY_DIM: int

class BuddyUI:
    def __init__(self) -> None: ...
    def update_identity(self, name: str, owner: str) -> None: ...
    def update_footer(self, stats: dict[str, object], battery: dict[str, object]) -> None: ...
    def set_connection(self, state: str) -> None: ...
    def clear_passkey(self) -> None: ...
    def show_passkey(self, pk: int) -> None: ...
    def flash_toast(self, text: str, color: int = ...) -> None: ...
    def update_heartbeat(self, hb: dict[str, object]) -> None: ...
    def restore_button_hints(self) -> None: ...
