"""Type stub for MicroPython's ``gc`` module.

Shadows CPython's real ``gc`` (which typeshed already covers), because this
repository's device code only ever calls ``collect()`` plus MicroPython's own
``mem_free()`` / ``mem_alloc()`` / ``threshold()`` — none of which exist on the
CPython side.
"""

def collect() -> None: ...
def mem_free() -> int: ...
def mem_alloc() -> int: ...
def threshold(amount: int = ...) -> int: ...
