"""Type stub for MicroPython's ``socket`` — the slice ``buddy/netlink.py`` uses.

CPython's typeshed ``socket`` is richer and differently shaped (``socket.socket``
takes family/type, ``recv`` returns ``bytes``, ...). The device only sees
MicroPython's, so the checker gets that surface and nothing more.
"""

SOL_SOCKET: int
SO_REUSEADDR: int

class socket:
    def __init__(self) -> None: ...
    def setsockopt(self, level: int, optname: int, value: int) -> None: ...
    def bind(self, address: tuple[str, int]) -> None: ...
    def listen(self, backlog: int) -> None: ...
    def setblocking(self, flag: bool) -> None: ...
    def accept(self) -> tuple[socket, tuple[str, int]]: ...
    def recv(self, bufsize: int) -> bytes: ...
    def send(self, data: bytes) -> int: ...
    def close(self) -> None: ...
